### ISSUE TITLE
Cambiar nombre de urls

### ISSUE THREAD

**Issue by RamsesMartinez** [DigimundoTesca/Pet-Guru#1]
en el archivo de urls de la app "home"
https://github.com/DigimundoTesca/Pet-Guru/blob/frontend/home/urls.py

```python
  url(r'^$', views.index, name='index.html'),    
  url(r'^nosotros/$', views.nosotros, name='nosotros.html'),
  url(r'^reglamento/$', views.reglamento, name='reglamento.html'),
```

cambiar a algo como esto:
```python
  url(r'^$', views.index, name='index'),    
  url(r'^nosotros/$', views.nosotros, name='nosotros'),
  url(r'^reglamento/$', views.reglamento, name='reglamento'),
```

Los __names__ de las url's son único y no se tienen que llamar precisamente igual que el template, puesto que son un alias para acceder a una vista de django.

**Comment by Itzli2000** [comment]
Solucionado en commit: efffa423770476a58d2c62f7d13f0ae81c626016
Se cierra issue
