### ISSUE TITLE
Crear carpeta de media para los settings

### ISSUE THREAD

**Issue by RamsesMartinez** [DigimundoTesca/Pet-Guru#28]
Además de añadir una carpeta donde se irán los archivos media (sólo para desarrollo) se deberá buscar la manera de estrucuturar las carpetas de acuerdo a la siguiente jerarquia:

Año (YYYY) -> Mes (MM) -> Día (DD)

**Comment by Itzli2000** [comment]
Completado en commit : 3cb48e3ec9764bcf52e38baaf2ef4a7538acb4fb

Falta crear jerarquia de carpetas
