### ISSUE TITLE
Mostrar información de pregunta

### ISSUE THREAD

**Issue by Itzli2000** [DigimundoTesca/Pet-Guru#61]
En sección pregunta -> Datos clinicos, mostrar toda la información de cada pregunta de forma dinámica

**Comment by JBasilio24** [comment]
ya envía toda la información falta darle diseño en el front
235b4453099e5d9d4a2ec7b4798fa74df78534f6

**Comment by Itzli2000** [comment]
Crear y enviar traducciones de los campos, para que se muestren en español

**Comment by Itzli2000** [comment]
Se debe cambiar 'Género' por 'Sexo'

**Comment by Itzli2000** [comment]
Completado en commit: ad77c1c536a3ee3e699801bf2c4ecb15a7a31a36
Se cierra issue
