### ISSUE TITLE
Exportar a excel

### ISSUE THREAD

**Issue by Itzli2000** [DigimundoTesca/Pet-Guru#93]
Crear una funcion que genere un excel con el total de usuarios con su rol y toda su informacion, y cuantas preguntas se han generado por especie

**Comment by JBasilio24** [comment]
59bd15bc46e5e0762f85c60e3d497a4dd3ec027f

**Comment by Itzli2000** [comment]
Completado en commit: 59bd15bc46e5e0762f85c60e3d497a4dd3ec027f
Se cierra issue
